### ISSUE TITLE
Undefined index: local_address

### ISSUE THREAD

**Issue by richardhedges** [steffjenl/laravel-azure-blob-storage#1]
Getting the following error code:
`Undefined index: local_address`

Usage examples:
`return response()->download(Storage::url($document->file), $document->file);`
`return response()->download(Storage::path($document->file), $document->file);`

It's referring to line 32 in `AzureBlobStorageServiceProvider.php`

Laravel version 5.8

**Comment by steffjenl** [comment]
I will fix this tommorow! Is that okay?

**Comment by steffjenl** [comment]
Fixed in 1.0.3!
